name: Release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DocxTemplater.sln'

    steps:
    - name: echo
      run: echo ${{ github.ref }}
      
    - uses: actions/checkout@v4 #Fetch all history for all tags and branches
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x.x
          7.x.x
          6.x.x

    - name: Restore
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Run tests
      run: dotnet test -c $BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v') == true
      run: dotnet nuget push **\*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{secrets.NUGET_API_KEY}}
